name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 18.0.2+101
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -B -V

      - name: SonarQube Analysis
        run: mvn verify sonar:sonar -Dsonar.host.url=${{secrets.SONAR_HOST_URL}}

        env:
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
          SONAR_LOGIN: ${{secrets.SONAR_LOGIN}}
